#!/usr/bin/env bash
#install nginx on a web server

apt-get update

apt-get install -y nginx

service nginx start

echo "events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        location / {
            return 200 'Hello World!\n';
            add_header Content-Type text/plain;
        }
    }
}" > /etc/nginx/nginx.conf

service nginx reload
