#!/usr/bin/env bash
#update config to redirect on /redirect_me

apt-get update
apt-get install -y nginx
service nginx start

REDIRECT='location = /redirect_me {return 301 "https://www.youtube.com/watch?v=PKffm2uI4dk";}'
FILE='/etc/nginx/sites-available/default'

if ! awk '/location = \/redirect_me/{found=1} END{if(!found) exit 1}' "$FILE"; then
    sed -i '/server_name _;/a \    '"$REDIRECT" "$FILE"
fi

service nginx reload
