#!/usr/bin/env bash
#update config to redirect on /redirect_me

sed -i '/^        listen 80;/a \        location /redirect_me {\n                return 301 https://youtu.be/PKffm2uI4dk?si=nj8e4kwkz4XGYpaZ;\n        }' /etc/nginx/nginx.conf

service nginx reload
