#!/usr/bin/env bash
#update config to redirect on /redirect_me

apt-get update
apt-get install -y nginx
service nginx start

printf "Redirect 301 /redirect_me https://youtu.be/PKffm2uI4dk?si=nj8e4kwkz4XGYpaZ\n" > /var/www/html/redirect_me

service nginx reload
