#!/usr/bin/env bash
#update config to have an not-found page

sed -i "/^        listen 80;/a \        error_page 404 /404.html;\n        location /404.html {\n                add_header Content-Type text;/plain\n                return 404 \"Ceci n'est pas une page\\n\";\n        }" /etc/nginx/nginx.conf

service nginx reload
