#!/usr/bin/env bash
#update config to redirect on /redirect_me

apt-get update
apt-get install -y nginx
service nginx start

printf "Ceci n'est pas une page\n\n" > /var/www/html/404
ERROR_PAGE='error_page 404 /404.html;'
FILE='/etc/nginx/sites-available/default'

printf "Hello World!\n" > /var/www/html/index.html;

REDIRECT='location = /redirect_me {return 301 "https://www.youtube.com/watch?v=PKffm2uI4dk";}'

if ! awk '/location \/redirect_me/{found=1} END{if(!found) exit 1}' "$FILE"; then
    sed -i '/server_name _;/a \    '"$REDIRECT" "$FILE"
fi

if ! awk '/error_page 404 \/404.html/{found=1} END{if(!found) exit 1}' "$FILE"; then
    sed -i '/server_name _;/a \    '"$ERROR_PAGE" "$FILE"
fi

nginx -s reload
