#!/usr/bin/env bash
# This script displays the content of the current directory in a list format
# Only the part of the name after the first dash is displayed
# Hidden files are not displayed

for file in *-*
do
   echo "${file#*-}"
done
